Repository team-MEETUS/meetup-server, pull requests merged in 2024-08, with the labels that each got.

#28 Feat/geo/#26 지역 조회
  src/main/java/site/mymeetup/meetupserver/geo/controller/GeoController.java
  src/main/java/site/mymeetup/meetupserver/geo/dto/GeoDto.java
  src/main/java/site/mymeetup/meetupserver/geo/entity/Geo.java
  src/main/java/site/mymeetup/meetupserver/geo/repository/GeoRepository.java
  src/main/java/site/mymeetup/meetupserver/geo/service/GeoService.java
  src/main/java/site/mymeetup/meetupserver/geo/service/GeoServiceImpl.java
Labels: ✨ Feature

#31 feat: 관심사 조회
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/interest/controller/InterestController.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestBigDto.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestSmallDto.java
  src/main/java/site/mymeetup/meetupserver/interest/entity/InterestBig.java
  src/main/java/site/mymeetup/meetupserver/interest/entity/InterestSmall.java
  src/main/java/site/mymeetup/meetupserver/interest/repository/InterestBigRepository.java
  src/main/java/site/mymeetup/meetupserver/interest/repository/InterestSmallRepository.java
  src/main/java/site/mymeetup/meetupserver/interest/service/InterestService.java
  src/main/java/site/mymeetup/meetupserver/interest/service/InterestServiceImpl.java
Labels: ✨ Feature

#32 feat: 모임 채팅 조회
  build.gradle
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/dto/ChatDto.java
  src/main/java/site/mymeetup/meetupserver/chat/entity/Chat.java
  src/main/java/site/mymeetup/meetupserver/chat/repository/ChatRepository.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatService.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ⚙️ Setting, ✨ Feature

#33 feat: crew 등록
  src/main/java/site/mymeetup/meetupserver/MeetupServerApplication.java
  src/main/java/site/mymeetup/meetupserver/common/service/S3ImageService.java
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/exception/GlobalExceptionHandler.java
  src/main/java/site/mymeetup/meetupserver/response/ApiResponse.java
Labels: ✨ Feature

#37 feat: crew 삭제
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#41 refactor: crew 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
Labels: 🔨 Refactor

#42 feat: 모임 상세 조회
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#48 feat: 모임멤버 엔티티 추가
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewAndMember.java
Labels: ✨ Feature

#52 feat: 모임 멤버 등록
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewMember.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#54 feat: 모임 가입 신청
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#66 feat: 특정 관심사 모임 조회
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/geo/repository/GeoRepository.java
Labels: ✨ Feature

#77 카테고리별 게시글 목록 조회
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#80 refactor: board 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
Labels: 🔨 Refactor

#83 feat: 모임 가입신청 내역 조회
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#86 feat: 게시글 조회
  src/main/java/site/mymeetup/meetupserver/board/dto/BoardDto.java
Labels: ✨ Feature

#88 refactor: crew 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/geo/controller/GeoController.java
  src/main/java/site/mymeetup/meetupserver/geo/dto/GeoDto.java
  src/main/java/site/mymeetup/meetupserver/geo/repository/GeoRepository.java
  src/main/java/site/mymeetup/meetupserver/geo/service/GeoService.java
  src/main/java/site/mymeetup/meetupserver/geo/service/GeoServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/interest/controller/InterestController.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestBigDto.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestSmallDto.java
  src/main/java/site/mymeetup/meetupserver/interest/repository/InterestBigRepository.java
  src/main/java/site/mymeetup/meetupserver/interest/repository/InterestSmallRepository.java
  src/main/java/site/mymeetup/meetupserver/interest/service/InterestService.java
  src/main/java/site/mymeetup/meetupserver/interest/service/InterestServiceImpl.java
Labels: 🔨 Refactor

#91 chore: crewMember 변수명 변경
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewMemberDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewMember.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🔨 Refactor

#92 feat: 게시글 삭제
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/entity/Board.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#93 feat: 채팅 등록, 조회 기능 구현
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/dto/ChatDto.java
  src/main/java/site/mymeetup/meetupserver/chat/entity/Chat.java
  src/main/java/site/mymeetup/meetupserver/chat/repository/ChatRepository.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatService.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/response/ApiResponse.java
Labels: ✨ Feature

#94 refactor: 모임원 역할 enum으로 관리
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewMemberDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewMember.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/role/CrewMemberRole.java
  src/main/java/site/mymeetup/meetupserver/crew/role/CrewMemberRoleConverter.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🔨 Refactor

#98 feat: 댓글 등록
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/dto/CommentDto.java
  src/main/java/site/mymeetup/meetupserver/board/entity/Comment.java
  src/main/java/site/mymeetup/meetupserver/board/repository/CommentRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#99 feat: 모임 찜 기능
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewLikeDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewLike.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewLikeRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#100 chore: cors 에러 수정
  src/main/java/site/mymeetup/meetupserver/config/WebConfig.java
Labels: 📬 API

#101 chore: 댓글 상태 변경
  src/main/java/site/mymeetup/meetupserver/board/dto/CommentDto.java
Labels: ✨ Feature

#103 feat: 사진첩 등록
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/dto/AlbumDto.java
  src/main/java/site/mymeetup/meetupserver/album/entity/Album.java
  src/main/java/site/mymeetup/meetupserver/album/repository/AlbumRepository.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#105 feat: 댓글 수정
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/entity/Comment.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#107 feat: 댓글 삭제
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/entity/Comment.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#108 feat: 모임 권한 관리
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewMemberDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/CrewMember.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#111 feat: 사진첩 조회
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/dto/AlbumDto.java
  src/main/java/site/mymeetup/meetupserver/album/repository/AlbumRepository.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
Labels: ✨ Feature

#113 fix: 모임원 관련 버그 수정
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🐞 Bug

#114 feat: 사진첩 상세 조회
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/repository/AlbumRepository.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#115 feat: 총 모임원 수 업데이트
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#117 feat: 모임원 ROLE 변경 및 모임 권한 변경 및 가입신청 수정
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/role/CrewMemberRole.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: ✨ Feature

#128 feat: 총 모임 찜 수 추가
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/entity/Crew.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#129 사진첩 좋아요
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/dto/AlbumLikeRespDto.java
  src/main/java/site/mymeetup/meetupserver/album/entity/AlbumLike.java
  src/main/java/site/mymeetup/meetupserver/album/repository/AlbumLikeRepository.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
Labels: ✨ Feature

#130 feat: 정모 등록
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/MeetingMember.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#131 feat: 정모 수정
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#132 feat: 정모 삭제 기능 추가
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#134 feat: 정모 조회
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#135 feat: 작성자 ID 값만 가져오도록 수정
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingDto.java
Labels: 🔨 Refactor

#136 feat: 자체 로그인
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/site/mymeetup/meetupserver/MeetupServerApplication.java
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTUtil.java
  src/main/java/site/mymeetup/meetupserver/jwt/LoginFilter.java
  src/main/java/site/mymeetup/meetupserver/member/dto/CustomUserDetails.java
  src/main/java/site/mymeetup/meetupserver/member/repository/MemberRepository.java
  src/main/java/site/mymeetup/meetupserver/member/service/CustomUserDetailsService.java
  src/main/resources/application.properties
Labels: ✨ Feature

#141 chore: security, jwt 검증 수정
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: 🔨 Refactor

#140 feat: 정모 참석
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#143 자체 로그인 리팩토링
  src/main/java/site/mymeetup/meetupserver/jwt/JWTUtil.java
  src/main/java/site/mymeetup/meetupserver/jwt/LoginFilter.java
Labels: 🔨 Refactor

#144 feat: 정모 참석 멤버 조회
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingMemberDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#145 게시글 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/dto/BoardDto.java
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: 🔨 Refactor

#146 feat: 정모 참석 거부
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingMemberDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: ✨ Feature

#148 refactor: 댓글 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/entity/Board.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#149 refactor: 로그인 전송 데이터 수정
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/LoginFilter.java
Labels: 🔨 Refactor

#150 chore: 시큐리티 검증하지 않을 URI 추가
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: 🔨 Refactor

#151 chore: 게시글 총 댓글 업데이트 수정
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#157 feat: 댓글 조회
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/dto/BoardDto.java
  src/main/java/site/mymeetup/meetupserver/board/dto/CommentDto.java
  src/main/java/site/mymeetup/meetupserver/board/repository/CommentRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: ✨ Feature

#158 Feat/board/#65
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: ✨ Feature

#160 refactor: 모임 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: 🔨 Refactor

#162 회원수정 관련 dto 분리 등 리팩토링
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
Labels: 🔨 Refactor

#163 refactor: 모임 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewMemberDto.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/role/CrewMemberRole.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/geo/dto/GeoDto.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestBigDto.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
Labels: 🔨 Refactor

#164 chore: security, jwt 검증 수정
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: 🔨 Refactor

#166 게시글, 댓글 Dto 전송 데이터 수정
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
  src/main/java/site/mymeetup/meetupserver/board/dto/BoardDto.java
  src/main/java/site/mymeetup/meetupserver/board/dto/CommentDto.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardService.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#172 deploy: secret 설정, 채팅 Spring Security 적용
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/site/mymeetup/meetupserver/config/MessageSecurityConfiguration.java
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/config/WebSocketConfig.java
  src/main/java/site/mymeetup/meetupserver/config/WebSocketInterceptor.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTUtil.java
  src/main/resources/application.properties
Labels: ✨ Feature, 🌏 Deploy

#173 refactor: security cors 에러 주석
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
Labels: 📬 API

#174 refactor: 정모 리팩토링
  src/main/java/site/mymeetup/meetupserver/meeting/controller/MeetingController.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/dto/MeetingMemberDto.java
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingService.java
  src/main/java/site/mymeetup/meetupserver/meeting/service/MeetingServiceImpl.java
Labels: 🔨 Refactor

#176 feat: 로그인한 유저가 해당 모임의 멤버인지 확인
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature

#178 refactor: 게시글 댓글 uri 수정
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
Labels: 🔨 Refactor

#179 Feat/board/#165
  src/main/java/site/mymeetup/meetupserver/board/control/BoardController.java
Labels: 🐞 Bug

#183 chore: CustomAccessDeniedHandler 제거
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/exception/CustomAccessDeniedHandler.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: 🔨 Refactor

#186 rafactor: ErrorCode HttpStatus 수정
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: 📬 API, 🔨 Refactor

#187 refactor: 모임 관련 수정
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: ✨ Feature, 🔨 Refactor

#188 feat: 채팅 jwt 검증
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/config/WebSocketInterceptor.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: ✨ Feature

#190 feat: 존재하지 않는 api 요청 커스텀
  src/main/java/site/mymeetup/meetupserver/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
Labels: ✨ Feature

#192 feat: 요청 url 유효성 검사
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature

#194 refactor: 댓글 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#197 refactor: 권한 변경시 role 타입 수정
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewMemberDto.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: 🔨 Refactor

#200 refactor: 가입 거절은 DEPARTED로 변경
  src/main/java/site/mymeetup/meetupserver/crew/role/CrewMemberRole.java
Labels: 🔨 Refactor

#201 feat: 사진첩 권한 확인
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
Labels: ✨ Feature

#203 chore: 사진첩 조회 dto 수정
  src/main/java/site/mymeetup/meetupserver/album/dto/AlbumDto.java
Labels: 🔨 Refactor

#205 refactor: ErrorCode 수정
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
Labels: 🔨 Refactor

#207 feat: 사진첩 페이징 처리
  src/main/java/site/mymeetup/meetupserver/album/control/AlbumController.java
  src/main/java/site/mymeetup/meetupserver/album/repository/AlbumRepository.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumService.java
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
Labels: ✨ Feature

#209 refactor: MemberController 수정
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
Labels: 🔨 Refactor

#210 feat: 자체 회원가입 문자인증
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/site/mymeetup/meetupserver/common/service/MessageService.java
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: ✨ Feature

#211 refactor: 자체회원가입 등 dto 수정
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
Labels: 🔨 Refactor

#212 refactor: 자체회원가입 비밀번호 관련 수정
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
Labels: 🔨 Refactor

#219 feat: 내 모임 조회 및 모임원 조회 쿼리 파라미터 예외처리
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewMemberRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature, 🔨 Refactor

#220 feat: 모임 검색 기능 추가
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature

#223 refactor: 게시글 댓글 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/repository/CommentRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#225 bug: 정모 관련 버그 수정
  src/main/java/site/mymeetup/meetupserver/meeting/repository/MeetingRepository.java
Labels: 🐞 Bug

#226 refactor: 관심사 별 모임 조회 버그 수정 및 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
Labels: 🔨 Refactor, 🐞 Bug

#227 feat: 새로 생긴 모임 조회
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature

#229 refactor: 사진첩 crewMember조회에서 특정 role인 멤버 조건 추가
  src/main/java/site/mymeetup/meetupserver/album/service/AlbumServiceImpl.java
Labels: 🔨 Refactor

#230 refactor: 회원가입, 로그인 수정
  src/main/java/site/mymeetup/meetupserver/jwt/LoginFilter.java
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/dto/CustomUserDetails.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
  src/main/java/site/mymeetup/meetupserver/member/oauth2/CustomSuccessHandler.java
  src/main/java/site/mymeetup/meetupserver/member/service/CustomOAuth2UserService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
Labels: 🔨 Refactor

#232 chore: 모임 dto 수정
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
Labels: 🔨 Refactor

#234 feat: 채팅 조회
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatService.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature, 🔨 Refactor

#235 refactor: 회원가입시 핸드폰, 상태값 등 검증
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/LoginFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/dto/CustomUserDetails.java
  src/main/java/site/mymeetup/meetupserver/member/dto/KakaoResponse.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
  src/main/java/site/mymeetup/meetupserver/member/dto/NaverResponse.java
  src/main/java/site/mymeetup/meetupserver/member/dto/OAuth2Resp.java
  src/main/java/site/mymeetup/meetupserver/member/oauth2/CustomSuccessHandler.java
  src/main/java/site/mymeetup/meetupserver/member/service/CustomOAuth2UserService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: 🔨 Refactor

#238 refactor: 게시글 목록 조회 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/repository/BoardRepository.java
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#239 refactor: 채팅 리팩토링
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/dto/ChatDto.java
  src/main/java/site/mymeetup/meetupserver/chat/repository/ChatRepository.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatService.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
Labels: 🔨 Refactor

#240 feat: 활동이 활발한 모임 조회
  src/main/java/site/mymeetup/meetupserver/chat/repository/ChatRepository.java
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/crew/controller/CrewController.java
  src/main/java/site/mymeetup/meetupserver/crew/dto/CrewDto.java
  src/main/java/site/mymeetup/meetupserver/crew/repository/CrewRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewService.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ✨ Feature

#241 refactor: 게시글 리팩토링
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#242 chore: 활발한 모임 조회 수정
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🔨 Refactor

#246 fix: 애플 시간대 버그 수정
  src/main/resources/application.properties
Labels: 🐞 Bug

#248 feat: MemberInfoDto 수정
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
Labels: ✨ Feature

#249 feat: sse 연결
  build.gradle
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
  src/main/java/site/mymeetup/meetupserver/notifacation/control/NotificationController.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: ✨ Feature

#251 rafactor: 채팅 security 수정
  src/main/java/site/mymeetup/meetupserver/config/SecurityConfig.java
  src/main/java/site/mymeetup/meetupserver/config/WebSocketConfig.java
  src/main/java/site/mymeetup/meetupserver/jwt/JWTFilter.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: 🔨 Refactor

#252 refactor: 로그인, 회원가입 phone, password 암호화
  build.gradle
  src/main/java/site/mymeetup/meetupserver/config/AES128.java
  src/main/java/site/mymeetup/meetupserver/member/dto/CustomUserDetails.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberDto.java
  src/main/java/site/mymeetup/meetupserver/member/entity/Member.java
  src/main/java/site/mymeetup/meetupserver/member/service/CustomUserDetailsService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: 🔨 Refactor

#256 refactor: 문자 인증 리팩토링
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: 🔨 Refactor

#257 feat: 댓글 알림
  src/main/java/site/mymeetup/meetupserver/board/service/BoardServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/entity/Notification.java
  src/main/java/site/mymeetup/meetupserver/notifacation/notification/NotificationRepository.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/type/NotificationType.java
Labels: ✨ Feature

#261 feat: 알림 조회
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
  src/main/java/site/mymeetup/meetupserver/notifacation/control/NotificationController.java
  src/main/java/site/mymeetup/meetupserver/notifacation/dto/NotificationDto.java
  src/main/java/site/mymeetup/meetupserver/notifacation/repository/NotificationRepository.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: ✨ Feature

#262 알림 개수 전송
  src/main/java/site/mymeetup/meetupserver/notifacation/repository/NotificationRepository.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: ✨ Feature

#263 feat: 알림 읽음 처리
  src/main/java/site/mymeetup/meetupserver/notifacation/control/NotificationController.java
  src/main/java/site/mymeetup/meetupserver/notifacation/entity/Notification.java
  src/main/java/site/mymeetup/meetupserver/notifacation/repository/NotificationRepository.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: ✨ Feature

#265 refactor: 마지막 채팅 시간은 단체 채팅 기준으로 수정
  src/main/java/site/mymeetup/meetupserver/chat/repository/ChatRepository.java
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🔨 Refactor

#266 refactor: 채팅 Dto 수정
  src/main/java/site/mymeetup/meetupserver/chat/dto/ChatDto.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
Labels: 🔨 Refactor

#268 refactor: Open Session in View 비활성화
  src/main/java/site/mymeetup/meetupserver/meeting/entity/Meeting.java
  src/main/resources/application.properties
Labels: 🔨 Refactor

#269 feat: 회원 관심사 등록, 수정 완료
  src/main/java/site/mymeetup/meetupserver/exception/ErrorCode.java
  src/main/java/site/mymeetup/meetupserver/interest/dto/InterestSmallDto.java
  src/main/java/site/mymeetup/meetupserver/interest/entity/InterestSmall.java
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
  src/main/java/site/mymeetup/meetupserver/member/controller/MemberController.java
  src/main/java/site/mymeetup/meetupserver/member/dto/MemberInterestDto.java
  src/main/java/site/mymeetup/meetupserver/member/entity/Member.java
  src/main/java/site/mymeetup/meetupserver/member/entity/MemberInterest.java
  src/main/java/site/mymeetup/meetupserver/member/repository/MemberInterestRepository.java
  src/main/java/site/mymeetup/meetupserver/member/repository/MemberRepository.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberService.java
  src/main/java/site/mymeetup/meetupserver/member/service/MemberServiceImpl.java
Labels: ✨ Feature

#271 관심사 조회 및 알림 리팩토링
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: 🔨 Refactor

#273 chore: maxLifetime 조정
  src/main/resources/application.properties
Labels: ⚙️ Setting

#275 feat: 모임 가입 신청 및 승인 알림
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/type/NotificationType.java
Labels: ✨ Feature

#278 deploy: 서버 TimeZone 설정
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#281 chore: 채팅 ChatSaveReqDto crewMemberRole 추가
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/dto/ChatDto.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
Labels: 🔨 Refactor

#283 채팅 동일 웹소켓 오류 해결
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatService.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#285 feat: 1:1 채팅 알림
  build.gradle
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationService.java
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
  src/main/java/site/mymeetup/meetupserver/notifacation/type/NotificationType.java
Labels: ✨ Feature

#287 chore: 웹소켓 cors 해결
  src/main/java/site/mymeetup/meetupserver/config/WebSocketConfig.java
Labels: 📬 API, 🔨 Refactor

#288 bug: 채팅 웹소켓 오류 해결
  src/main/java/site/mymeetup/meetupserver/chat/control/ChatController.java
  src/main/java/site/mymeetup/meetupserver/chat/service/ChatServiceImpl.java
Labels: 🐞 Bug

#290 chore: 알림 url 추가
  src/main/java/site/mymeetup/meetupserver/jwt/UrlValidationFilter.java
Labels: ⚙️ Setting

#295 fix: 일반멤버는 탈퇴가 안되는 버그 해결
  src/main/java/site/mymeetup/meetupserver/crew/service/CrewServiceImpl.java
Labels: 🐞 Bug

#296 chore: 채팅 알림 url 수정
  src/main/java/site/mymeetup/meetupserver/notifacation/service/NotificationServiceImpl.java
Labels: 🔨 Refactor
